package com.example.utils

import com.example.data.models.SupportedLanguage

object MultilingualManager {

    private val translations = mapOf(
        SupportedLanguage.ENGLISH to mapOf(
            // App & Branding
            "app_title" to "HaathSe",
            "tagline" to "Your craft. Your story. Your business.",
            "role_artisan" to "Artisan Studio",
            "role_buyer" to "B2B Buyer Portal",
            "role_admin" to "Ministry / NGO Portal",
            "good_morning" to "Good day",
            "business_today" to "Your business today",
            "estimated_sales" to "Estimated Sales",
            "active_products" to "Live Products",
            "buyer_requests" to "Buyer Requests (RFQ)",
            "sell_new_product" to "One-Tap Sell Product",
            "speak_about_product" to "Speak about your product",
            "ai_coach_tip" to "AI Business Tip",
            "my_products" to "My Catalog",
            "orders" to "Orders & Stock",
            "materials_ledger" to "Material Ledger",
            "simple_mode" to "Simple Voice Mode",
            "craft_map" to "India Craft Map",
            "govt_schemes" to "Govt Schemes",
            "qr_story" to "Craft QR Passport",
            "listing_score" to "AI Listing Score",
            "fair_price" to "Fair Sustainable Price",
            "publish_button" to "Publish to B2B Marketplace",
            "verified_badge" to "Verified Heritage Craft",
            "quick_sale" to "Quick Sale",
            "fair_value" to "Fair Value",
            "premium" to "Premium Craft",
            "voice_recording_hint" to "Tap microphone & speak in your native language...",
            "audio_read_aloud" to "Listen in Audio",
            "translating_to_buyer" to "Translated for Buyer",
            "minimum_sustainable_price" to "Minimum Sustainable Price",
            "raw_materials" to "Raw Materials",
            "craft_story" to "Story Behind the Craft",
            "rfq_bulk_request" to "Bulk Requirement (RFQ)",
            "smart_match_score" to "AI Smart Match Score",
            "negotiation_tip" to "Fair Deal AI Advice",

            // Navigation & Common Actions
            "Home" to "Home",
            "Products" to "Products",
            "Add" to "Add",
            "Circles" to "Circles",
            "Profile" to "Profile",
            "Explore" to "Explore",
            "Post RFQ" to "Post RFQ",
            "Chat" to "Chat",
            "Impact" to "Impact",
            "Schemes" to "Schemes",
            "Notifications" to "Notifications",
            "Save" to "Save",
            "Cancel" to "Cancel",
            "Back" to "Back",
            "Next" to "Next",
            "Publish" to "Publish",
            "Take Photo" to "Take Photo",
            "Enhance Photo" to "Enhance Photo",
            "Generate Story" to "Generate Story",
            "View Details" to "View Details",
            "Login" to "Login",
            "Register" to "Register",
            "Logout" to "Logout",
            "Filter" to "Filter",
            "Search" to "Search",
            "Order Now" to "Order Now",
            "Call" to "Call",
            "Message" to "Message",
            "Download QR" to "Download QR",
            "Share" to "Share",
            "Delete" to "Delete",
            "Edit" to "Edit",
            "Camera Guidance" to "Camera Guidance",
            "Studio Pro" to "Studio Pro",
            "Heritage Warm" to "Heritage Warm",
            "Vibrant Detail" to "Vibrant Detail",
            "Move closer" to "Move closer to capture fine weave texture",
            "Hold steady" to "Hold camera steady and level",
            "Too dark" to "Lighting is too dark. Move near light or turn on flash",
            "Too bright" to "Too bright glare. Move slightly away from direct sun",
            "Perfect shot" to "Perfect framing! Tap the shutter button now",

            // Role selection
            "Welcome to HaathSe" to "Welcome to HaathSe",
            "Made by hand. Powered by people and AI." to "Made by hand. Powered by people and AI.",
            "Choose your role to get started" to "Choose your role to get started",
            "I am an Artisan / Maker" to "I am an Artisan / Maker",
            "I am a B2B Buyer / Retailer" to "I am a B2B Buyer / Retailer",
            "Ministry & NGO Monitor" to "Ministry & NGO Monitor",
            "Sell crafts, get fair prices, create digital passport" to "Sell crafts, get fair prices, create digital passport",
            "Source authentic handmade heritage goods directly" to "Source authentic handmade heritage goods directly",
            "Track artisan clusters, sales impact and GI verification" to "Track artisan clusters, sales impact and GI verification",
            "Enter Artisan Studio" to "Enter Artisan Studio",
            "Enter Buyer Portal" to "Enter Buyer Portal",
            "Enter Impact Hub" to "Enter Impact Hub",

            // Artisan Dashboard & Features
            "Artisan Command Center" to "Artisan Command Center",
            "Voice AI Saathi" to "Voice AI Saathi",
            "Ask Saathi anything in your voice..." to "Ask Saathi anything in your voice...",
            "Recent Orders" to "Recent Orders",
            "Active Catalog" to "Active Catalog",
            "Quick Actions" to "Quick Actions",
            "Materials & Inventory" to "Materials & Inventory",
            "Market Trends & Pulse" to "Market Trends & Pulse",
            "Artisan Community Circles" to "Artisan Community Circles",
            "Exhibitions & Fairs" to "Exhibitions & Fairs",
            "Business Health Score" to "Business Health Score",
            "Total Revenue" to "Total Revenue",
            "Pending Orders" to "Pending Orders",
            "Completed" to "Completed",
            "Shipped" to "Shipped",
            "Processing" to "Processing",
            "New Inquiries" to "New Inquiries",
            "Fair Price Breakdown" to "Fair Price Breakdown",
            "Material Cost" to "Material Cost",
            "Labor Hours" to "Labor Hours",
            "Artisan Margin" to "Artisan Margin",
            "Recommended Price" to "Recommended Price",
            "Minimum Sustainable" to "Minimum Sustainable",
            "B2B Wholesale Price" to "B2B Wholesale Price",
            "Suggested Retail" to "Suggested Retail"
        ),
        SupportedLanguage.HINDI to mapOf(
            // App & Branding
            "app_title" to "HaathSe (हात से)",
            "tagline" to "आपका शिल्प। आपकी कहानी। आपका व्यवसाय।",
            "role_artisan" to "कारीगर स्टूडियो",
            "role_buyer" to "B2B खरीदार पोर्टल",
            "role_admin" to "मंत्रालय / NGO पोर्टल",
            "good_morning" to "नमस्ते",
            "business_today" to "आज का व्यवसाय",
            "estimated_sales" to "अनुमानित बिक्री",
            "active_products" to "सक्रिय उत्पाद",
            "buyer_requests" to "खरीदार अनुरोध (RFQ)",
            "sell_new_product" to "एक-टैप में उत्पाद बेचें",
            "speak_about_product" to "अपने उत्पाद के बारे में बोलें",
            "ai_coach_tip" to "AI बिज़नेस कोच सलाह",
            "my_products" to "मेरा कैटलॉग",
            "orders" to "ऑर्डर और स्टॉक",
            "materials_ledger" to "कच्चा माल बहीखाता",
            "simple_mode" to "सरल वॉइस मोड",
            "craft_map" to "भारत शिल्प मानचित्र",
            "govt_schemes" to "सरकारी योजनाएं",
            "qr_story" to "शिल्प QR पासपोर्ट",
            "listing_score" to "AI लिस्टिंग स्कोर",
            "fair_price" to "उचित टिकाऊ मूल्य",
            "publish_button" to "B2B बाज़ार में प्रकाशित करें",
            "verified_badge" to "सत्यापित पारंपरिक शिल्प",
            "quick_sale" to "त्वरित बिक्री",
            "fair_value" to "उचित मूल्य",
            "premium" to "प्रीमियम शिल्प",
            "voice_recording_hint" to "माइक दबाएं और अपनी भाषा में बोलें...",
            "audio_read_aloud" to "ऑडियो में सुनें",
            "translating_to_buyer" to "खरीदार हेतु अनुवादित",
            "minimum_sustainable_price" to "न्यूनतम टिकाऊ मूल्य",
            "raw_materials" to "कच्चा माल",
            "craft_story" to "शिल्प की अनमोल कहानी",
            "rfq_bulk_request" to "थोक ऑर्डर अनुरोध (RFQ)",
            "smart_match_score" to "AI स्मार्ट मैच स्कोर",
            "negotiation_tip" to "उचित सौदे की सलाह",

            // Navigation & Common Actions
            "Home" to "होम",
            "Products" to "उत्पाद",
            "Add" to "जोड़ें",
            "Circles" to "मंडलियां",
            "Profile" to "प्रोफाइल",
            "Explore" to "एक्सप्लोर",
            "Post RFQ" to "मांग पोस्ट करें",
            "Chat" to "चैट",
            "Impact" to "प्रभाव",
            "Schemes" to "योजनाएं",
            "Notifications" to "सूचनाएं",
            "Save" to "सहेजें",
            "Cancel" to "रद्द करें",
            "Back" to "पीछे",
            "Next" to "आगे",
            "Publish" to "प्रकाशित करें",
            "Take Photo" to "फोटो लें",
            "Enhance Photo" to "फोटो संवारें",
            "Generate Story" to "कहानी बनाएं",
            "View Details" to "विवरण देखें",
            "Login" to "लॉग इन",
            "Register" to "रजिस्टर करें",
            "Logout" to "लॉग आउट",
            "Filter" to "फ़िल्टर",
            "Search" to "खोजें",
            "Order Now" to "ऑर्डर करें",
            "Call" to "कॉल करें",
            "Message" to "संदेश भेजें",
            "Download QR" to "QR डाउनलोड करें",
            "Share" to "साझा करें",
            "Delete" to "हटाएं",
            "Edit" to "संपादित करें",
            "Camera Guidance" to "कैमरा मार्गदर्शन",
            "Studio Pro" to "स्टूडियो प्रो",
            "Heritage Warm" to "हेरिटेज वॉर्म",
            "Vibrant Detail" to "वाइब्रेंट डिटेल",
            "Move closer" to "बारीक बुनाई और बनावट के लिए कैमरे को थोड़ा पास लाएं",
            "Hold steady" to "कैमरा स्थिर और सीधा रखें",
            "Too dark" to "रोशनी कम है। प्रकाश में आएं या फ्लैश चालू करें",
            "Too bright" to "अधिक चमक है। सीधी धूप से थोड़ा हटें",
            "Perfect shot" to "बिल्कुल सही फ्रेमिंग! अभी फोटो खींचें",

            // Role selection
            "Welcome to HaathSe" to "हात से (HaathSe) में आपका स्वागत है",
            "Made by hand. Powered by people and AI." to "हाथों से निर्मित। तकनीक और AI द्वारा सशक्त।",
            "Choose your role to get started" to "शुरू करने के लिए अपनी भूमिका चुनें",
            "I am an Artisan / Maker" to "मैं एक कारीगर / निर्माता हूँ",
            "I am a B2B Buyer / Retailer" to "मैं एक B2B खरीदार / व्यापारी हूँ",
            "Ministry & NGO Monitor" to "मंत्रालय एवं NGO पोर्टल",
            "Sell crafts, get fair prices, create digital passport" to "शिल्प बेचें, सही मूल्य पाएं और डिजिटल पासपोर्ट बनाएं",
            "Source authentic handmade heritage goods directly" to "सीधे प्रामाणिक हस्तशिल्प और पारंपरिक उत्पाद खरीदें",
            "Track artisan clusters, sales impact and GI verification" to "कारीगर समूहों, बिक्री प्रभाव और प्रमाणन को ट्रैक करें",
            "Enter Artisan Studio" to "कारीगर स्टूडियो में जाएं",
            "Enter Buyer Portal" to "खरीदार पोर्टल में जाएं",
            "Enter Impact Hub" to "इम्पैक्ट हब में जाएं",

            // Artisan Dashboard & Features
            "Artisan Command Center" to "कारीगर कमान केंद्र",
            "Voice AI Saathi" to "वॉयस AI साथी",
            "Ask Saathi anything in your voice..." to "अपनी आवाज़ में साथी से कुछ भी पूछें...",
            "Recent Orders" to "हाल के ऑर्डर",
            "Active Catalog" to "सक्रिय कैटलॉग",
            "Quick Actions" to "त्वरित क्रियाएं",
            "Materials & Inventory" to "कच्चा माल और स्टॉक",
            "Market Trends & Pulse" to "बाज़ार के रुझान और मांग",
            "Artisan Community Circles" to "कारीगर समुदाय मंडलियां",
            "Exhibitions & Fairs" to "शिल्प मेले और प्रदर्शनियां",
            "Business Health Score" to "व्यवसाय स्वास्थ्य स्कोर",
            "Total Revenue" to "कुल कमाई",
            "Pending Orders" to "लंबित ऑर्डर",
            "Completed" to "पूर्ण",
            "Shipped" to "भेज दिया गया",
            "Processing" to "प्रक्रिया में",
            "New Inquiries" to "नई पूछताछ",
            "Fair Price Breakdown" to "उचित मूल्य का विवरण",
            "Material Cost" to "कच्चे माल की लागत",
            "Labor Hours" to "परिश्रम के घंटे",
            "Artisan Margin" to "कारीगर का मुनाफा",
            "Recommended Price" to "अनुशंसित मूल्य",
            "Minimum Sustainable" to "न्यूनतम टिकाऊ मूल्य",
            "B2B Wholesale Price" to "B2B थोक मूल्य",
            "Suggested Retail" to "सुझाया गया खुदरा मूल्य"
        ),
        SupportedLanguage.TAMIL to mapOf(
            // App & Branding
            "app_title" to "HaathSe (ஹாத்ஸே)",
            "tagline" to "உங்கள் கைவினை. உங்கள் கதை. உங்கள் வணிகம்.",
            "role_artisan" to "கைவினைஞர் ஸ்டுடியோ",
            "role_buyer" to "B2B வாங்குபவர் தளம்",
            "role_admin" to "அரசு / NGO தளம்",
            "good_morning" to "வணக்கம்",
            "business_today" to "இன்றைய வணிகம்",
            "estimated_sales" to "மதிப்பிடப்பட்ட விற்பனை",
            "active_products" to "நேரலை பொருட்கள்",
            "buyer_requests" to "மொத்த கோரிக்கைகள் (RFQ)",
            "sell_new_product" to "ஒரே தட்டலில் விற்கவும்",
            "speak_about_product" to "உங்கள் கைவினை பற்றி பேசுங்கள்",
            "ai_coach_tip" to "AI வணிக வழிகாட்டி",
            "my_products" to "என் தயாரிப்புகள்",
            "orders" to "ஆர்டர்கள் & இருப்பு",
            "materials_ledger" to "மூலப்பொருள் கணக்கு",
            "simple_mode" to "எளிய குரல் பயன்முறை",
            "craft_map" to "இந்திய கைவினை வரைபடம்",
            "govt_schemes" to "அரசு திட்டங்கள்",
            "qr_story" to "கைவினை QR பாஸ்போர்ட்",
            "listing_score" to "AI பட்டியல் தரம்",
            "fair_price" to "நியாயமான நிலையான விலை",
            "publish_button" to "B2B சந்தையில் வெளியிடவும்",
            "verified_badge" to "சரிபார்க்கப்பட்ட பாரம்பரியம்",
            "quick_sale" to "விரைவு விற்பனை",
            "fair_value" to "நியாய விலை",
            "premium" to "பிரீமியம் மதிப்பு",
            "voice_recording_hint" to "மைக் அழுத்தி தமிழில் பேசுங்கள்...",
            "audio_read_aloud" to "குரலில் கேட்க",
            "translating_to_buyer" to "வாங்குபவருக்கான மொழிபெயர்ப்பு",
            "minimum_sustainable_price" to "குறைந்தபட்ச நிலையான விலை",
            "raw_materials" to "மூலப்பொருட்கள்",
            "craft_story" to "கைவினைக்கு பின்னணியான கதை",
            "rfq_bulk_request" to "மொத்த ஆர்டர் கோரிக்கை",
            "smart_match_score" to "AI ஸ்மார்ட் மேட்ச் மதிப்பெண்",
            "negotiation_tip" to "நியாயமான பேரம் வழிகாட்டல்",

            // Navigation & Common Actions
            "Home" to "முகப்பு",
            "Products" to "பொருட்கள்",
            "Add" to "சேர்",
            "Circles" to "குழுக்கள்",
            "Profile" to "சுயவிவரம்",
            "Explore" to "ஆராய்க",
            "Post RFQ" to "கோரிக்கை இடுக",
            "Chat" to "உரையாடல்",
            "Impact" to "தாக்கம்",
            "Schemes" to "திட்டங்கள்",
            "Notifications" to "அறிவிப்புகள்",
            "Save" to "சேமி",
            "Cancel" to "ரத்துசெய்",
            "Back" to "பின்செல்",
            "Next" to "அடுத்து",
            "Publish" to "வெளியிடு",
            "Take Photo" to "புகைப்படம் எடு",
            "Enhance Photo" to "மெருகூட்டு",
            "Generate Story" to "கதை உருவாக்கு",
            "View Details" to "விவரம் காண்க",
            "Login" to "உள்நுழைக",
            "Register" to "பதிவுசெய்க",
            "Logout" to "வெளியேறு",
            "Filter" to "வடிகட்டு",
            "Search" to "தேடுக",
            "Order Now" to "ஆர்டர் செய்",
            "Call" to "அழைக்க",
            "Message" to "செய்தி அனுப்பு",
            "Download QR" to "QR பதிவிறக்கு",
            "Share" to "பகிர்",
            "Delete" to "நீக்கு",
            "Edit" to "திருத்து",
            "Camera Guidance" to "கேமரா வழிகாட்டல்",
            "Studio Pro" to "ஸ்டுடியோ ப்ரோ",
            "Heritage Warm" to "பாரம்பரிய பொலிவு",
            "Vibrant Detail" to "வண்ண நுணுக்கம்",
            "Move closer" to "நெசவின் நுணுக்கங்களை எடுக்க கேமராவை இன்னும் கொஞ்சம் அருகில் கொண்டு வாருங்கள்",
            "Hold steady" to "கை அசைக்காமல் கேமராவை நேராகப் பிடியுங்கள்",
            "Too dark" to "வெளிச்சம் குறைவாக உள்ளது. வெளிச்சத்திற்கு வாருங்கள் அல்லது ஃபிளாஷ் இயக்கவும்",
            "Too bright" to "அதிக வெளிச்சம். நேரடி சூரிய ஒளியில் இருந்து சற்று விலகுங்கள்",
            "Perfect shot" to "சரியான கோணம்! இப்போது புகைப்படம் எடுங்கள்",

            // Role selection
            "Welcome to HaathSe" to "ஹாத்ஸே-க்கு நல்வரவு",
            "Made by hand. Powered by people and AI." to "கைவினைப் பெருமை. AI தொழில்நுட்ப ஆற்றல்.",
            "Choose your role to get started" to "தொடங்க உங்கள் பொறுப்பைத் தேர்ந்தெடுக்கவும்",
            "I am an Artisan / Maker" to "நான் ஒரு கைவினைஞர் / உற்பத்தியாளர்",
            "I am a B2B Buyer / Retailer" to "நான் ஒரு B2B வாங்குபவர் / வணிகர்",
            "Ministry & NGO Monitor" to "அரசு மற்றும் NGO கண்காணிப்பு",
            "Sell crafts, get fair prices, create digital passport" to "பொருட்களை விற்க, நியாய விலை பெற, டிஜிட்டல் பாஸ்போர்ட் பெற",
            "Source authentic handmade heritage goods directly" to "நேரடியாக அசல் கைவினைப் பொருட்களை மொத்தமாக வாங்க",
            "Track artisan clusters, sales impact and GI verification" to "கைவினைஞர் குழுக்கள் மற்றும் விற்பனை தாக்கத்தை கண்காணிக்க",
            "Enter Artisan Studio" to "கைவினைஞர் தளத்திற்குள் செல்க",
            "Enter Buyer Portal" to "வாங்குபவர் தளத்திற்குள் செல்க",
            "Enter Impact Hub" to "தாக்க மையத்திற்குள் செல்க",

            // Artisan Dashboard & Features
            "Artisan Command Center" to "கைவினைஞர் கட்டுப்பாட்டு மையம்",
            "Voice AI Saathi" to "குரல் AI சாதி",
            "Ask Saathi anything in your voice..." to "உங்கள் குரலில் சாதியிடம் எதையும் கேளுங்கள்...",
            "Recent Orders" to "சமீபத்திய ஆர்டர்கள்",
            "Active Catalog" to "செயலில் உள்ள பட்டியல்",
            "Quick Actions" to "விரைவுச் செயல்கள்",
            "Materials & Inventory" to "மூலப்பொருட்கள் & இருப்பு",
            "Market Trends & Pulse" to "சந்தை தேவைகளும் நிலவரமும்",
            "Artisan Community Circles" to "கைவினைஞர் சமூகக் குழுக்கள்",
            "Exhibitions & Fairs" to "கைவினை கண்காட்சிகள்",
            "Business Health Score" to "வணிக நல்வாழ்வு குறியீடு",
            "Total Revenue" to "மொத்த வருவாய்",
            "Pending Orders" to "நிலுவையில் உள்ளவை",
            "Completed" to "நிறைவடைந்தது",
            "Shipped" to "அனுப்பப்பட்டது",
            "Processing" to "செயலாக்கத்தில்",
            "New Inquiries" to "புதிய விசாரணைகள்",
            "Fair Price Breakdown" to "நியாய விலை விவரம்",
            "Material Cost" to "மூலப்பொருள் அடக்கவிலை",
            "Labor Hours" to "உழைப்பு நேரம்",
            "Artisan Margin" to "கைவினைஞர் லாபம்",
            "Recommended Price" to "பரிந்துரைக்கப்பட்ட விலை",
            "Minimum Sustainable" to "குறைந்தபட்ச நிலையான விலை",
            "B2B Wholesale Price" to "B2B மொத்த விலை",
            "Suggested Retail" to "சில்லறை விற்பனை விலை"
        ),
        SupportedLanguage.TELUGU to mapOf(
            "app_title" to "HaathSe (హాత్‌సే)",
            "tagline" to "మీ కళ. మీ కథ. మీ వ్యాపారం.",
            "role_artisan" to "కళాకారుల స్టూడియో",
            "role_buyer" to "B2B కొనుగోలుదారు పోర్టల్",
            "role_admin" to "ప్రభుత్వ / NGO పోర్టల్",
            "good_morning" to "నమస్కారం",
            "business_today" to "ఈ రోజు మీ వ్యాపారం",
            "estimated_sales" to "అంచనా అమ్మకాలు",
            "active_products" to "ఉత్పత్తులు",
            "buyer_requests" to "కొనుగోలుదారు అభ్యర్థనలు",
            "sell_new_product" to "ఉత్పత్తిని అమ్మండి",
            "speak_about_product" to "మీ ఉత్పత్తి గురించి మాట్లాడండి",
            "ai_coach_tip" to "AI వ్యాపార సలహా",
            "my_products" to "నా ఉత్పత్తులు",
            "orders" to "ఆర్డర్లు & నిల్వలు",
            "materials_ledger" to "ముడి సరుకు లెక్కలు",
            "simple_mode" to "సులభమైన వాయిస్ మోడ్",
            "craft_map" to "భారతీయ హస్తకళల మ్యాప్",
            "govt_schemes" to "ప్రభుత్వ పథకాలు",
            "qr_story" to "కళ QR పాస్‌పోర్ట్",
            "listing_score" to "AI లిస్టింగ్ స్కోరు",
            "fair_price" to "సమంజసమైన స్థిర ధర",
            "publish_button" to "B2B మార్కెట్‌లో ప్రచురించండి",
            "verified_badge" to "ధృవీకరించబడిన కళ",
            "quick_sale" to "త్వరిత విక్రయం",
            "fair_value" to "సమంజసమైన ధర",
            "premium" to "ప్రీమియం ధర",
            "voice_recording_hint" to "మైక్ నొక్కి తెలుగులో మాట్లాడండి...",
            "audio_read_aloud" to "వినండి",
            "translating_to_buyer" to "కొనుగోలుదారు కోసం అనువాదం",
            "minimum_sustainable_price" to "కనిష్ట స్థిర ధర",
            "raw_materials" to "ముడి పదార్థాలు",
            "craft_story" to "హస్తకళ వెనుక ఉన్న కథ",
            "rfq_bulk_request" to "బల్క్ ఆర్డర్ అభ్యర్థన",
            "smart_match_score" to "AI స్మార్ట్ మ్యాచ్ స్కోరు",
            "negotiation_tip" to "సమంజసమైన ఒప్పంద సలహా",

            "Home" to "హోమ్",
            "Products" to "ఉత్పత్తులు",
            "Add" to "జోడించండి",
            "Circles" to "సమూహాలు",
            "Profile" to "ప్రొఫైల్",
            "Explore" to "అన్వేషించండి",
            "Post RFQ" to "అభ్యర్థన పంపండి",
            "Chat" to "చాట్",
            "Impact" to "ప్రభావం",
            "Schemes" to "పథకాలు",
            "Notifications" to "నోటిఫికేషన్లు",
            "Save" to "సేవ్ చేయండి",
            "Cancel" to "రద్దు చేయండి",
            "Back" to "వెనుకకు",
            "Next" to "తరువాత",
            "Publish" to "ప్రచురించండి",
            "Take Photo" to "ఫోటో తీయండి",
            "Enhance Photo" to "మెరుగుపరచండి",
            "Generate Story" to "కథను సృష్టించండి",
            "View Details" to "వివరాలు చూడండి",
            "Login" to "లాగిన్",
            "Register" to "రిజిస్టర్",
            "Logout" to "లాగ్ అవుట్",
            "Filter" to "ఫిల్టర్",
            "Search" to "శోధించండి",
            "Order Now" to "ఆర్డర్ చేయండి",
            "Call" to "కాల్",
            "Message" to "సందేశం",
            "Download QR" to "QR డౌన్‌లోడ్",
            "Share" to "షేర్",
            "Delete" to "తొలగించండి",
            "Edit" to "సవరించండి",
            "Camera Guidance" to "కెమెరా మార్గదర్శకత్వం",
            "Studio Pro" to "స్టూడియో ప్రో",
            "Heritage Warm" to "వారసత్వ కాంతి",
            "Vibrant Detail" to "స్పష్టమైన వివరాలు",
            "Move closer" to "నేత నమూనాల కోసం కెమెరాను దగ్గరకు జరపండి",
            "Hold steady" to "కెమెరాను కదలకుండా స్థిరంగా పట్టుకోండి",
            "Too dark" to "వెలుతురు తక్కువగా ఉంది. కాంతిలోకి రండి లేదా ఫ్లాష్ ఆన్ చేయండి",
            "Too bright" to "ఎక్కువ వెలుతురు ఉంది. ఎండ నుండి కొద్దిగా పక్కకు రండి",
            "Perfect shot" to "సరైన కోణం! ఇప్పుడు ఫోటో తీయండి",

            "Welcome to HaathSe" to "హాత్‌సేకి స్వాగతం",
            "Made by hand. Powered by people and AI." to "చేతితో చేసినది. మానవ మరియు AI శక్తితో.",
            "Choose your role to get started" to "ప్రారంభించడానికి మీ పాత్రను ఎంచుకోండి",
            "I am an Artisan / Maker" to "నేను ఒక కళాకారుడిని / తయారీదారుని",
            "I am a B2B Buyer / Retailer" to "నేను B2B కొనుగోలుదారుడిని / వ్యాపారిని",
            "Ministry & NGO Monitor" to "ప్రభుత్వ మరియు NGO పర్యవేక్షణ",
            "Sell crafts, get fair prices, create digital passport" to "కళలను అమ్మండి, సరైన ధర పొందండి, డిజిటల్ పాస్‌పోర్ట్ రూపొందించండి",
            "Source authentic handmade heritage goods directly" to "ప్రత్యక్షంగా అసలైన చేతివృత్తుల వస్తువులను కొనుగోలు చేయండి",
            "Track artisan clusters, sales impact and GI verification" to "కళాకారుల సమూహాలు, విక్రయాల ప్రభావాన్ని ట్రాక్ చేయండి",
            "Enter Artisan Studio" to "కళాకారుల స్టూడియోలోకి వెళ్లండి",
            "Enter Buyer Portal" to "కొనుగోలుదారుల పోర్టల్‌లోకి వెళ్లండి",
            "Enter Impact Hub" to "ఇంపాక్ట్ హబ్‌లోకి వెళ్లండి"
        ),
        SupportedLanguage.KANNADA to mapOf(
            "app_title" to "HaathSe (ಹಾತ್‌ಸೆ)",
            "tagline" to "ನಿಮ್ಮ ಕಲೆ. ನಿಮ್ಮ ಕಥೆ. ನಿಮ್ಮ ವ್ಯಾಪಾರ.",
            "role_artisan" to "ಕುಶಲಕರ್ಮಿ ಸ್ಟುಡಿಯೋ",
            "role_buyer" to "B2B ಖರೀದಿದಾರ ಪೋರ್ಟಲ್",
            "role_admin" to "ಸರ್ಕಾರಿ / NGO ಪೋರ್ಟಲ್",
            "good_morning" to "ನಮಸ್ಕಾರ",
            "business_today" to "ಇಂದಿನ ವ್ಯಾಪಾರ",
            "estimated_sales" to "ಅಂದಾಜು ಮಾರಾಟ",
            "active_products" to "ಉತ್ಪನ್ನಗಳು",
            "buyer_requests" to "ಖರೀದಿದಾರರ ಬೇಡಿಕೆ",
            "sell_new_product" to "ಉತ್ಪನ್ನ ಮಾರಾಟ ಮಾಡಿ",
            "speak_about_product" to "ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಬಗ್ಗೆ ಮಾತನಾಡಿ",
            "ai_coach_tip" to "AI ವ್ಯವಹಾರ ಮಾರ್ಗದರ್ಶಿ",
            "my_products" to "ನನ್ನ ಉತ್ಪನ್ನಗಳು",
            "orders" to "ಆರ್ಡರ್‌ಗಳು & ದಾಸ್ತಾನು",
            "materials_ledger" to "ಕಚ್ಚಾವಸ್ತುಗಳ ಲೆಕ್ಕ",
            "simple_mode" to "ಸರಳ ಧ್ವನಿ ಮೋಡ್",
            "craft_map" to "ಭಾರತದ ಕರಕುಶಲ ನಕ್ಷೆ",
            "govt_schemes" to "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
            "qr_story" to "ಕರಕುಶಲ QR ಪಾಸ್‌ಪೋರ್ಟ್",
            "listing_score" to "AI ಪಟ್ಟಿ ಸ್ಕೋರ್",
            "fair_price" to "ಸಮಂಜಸವಾದ ಸುಸ್ಥಿರ ಬೆಲೆ",
            "publish_button" to "B2B ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಪ್ರಕಟಿಸಿ",
            "verified_badge" to "ದೃಢೀಕೃತ ಸಾಂಪ್ರದಾಯಿಕ ಕಲೆ",
            "quick_sale" to "ತ್ವರಿತ ಮಾರಾಟ",
            "fair_value" to "ಸಮಂಜಸ ಬೆಲೆ",
            "premium" to "ಪ್ರೀಮಿಯಂ ಬೆಲೆ",
            "voice_recording_hint" to "ಮೈಕ್ ಒತ್ತಿ ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ...",
            "audio_read_aloud" to "ಆಡಿಯೋದಲ್ಲಿ ಕೇಳಿ",
            "translating_to_buyer" to "ಖರೀದಿದಾರರಿಗೆ ಅನುವಾದಿಸಲಾಗಿದೆ",
            "minimum_sustainable_price" to "ಕನಿಷ್ಠ ಸುಸ್ಥಿರ ಬೆಲೆ",
            "raw_materials" to "ಕಚ್ಚಾ ವಸ್ತುಗಳು",
            "craft_story" to "ಕಲೆಯ ಹಿನ್ನೆಲೆಯ ಕಥೆ",
            "rfq_bulk_request" to "ಬೃಹತ್ ಆರ್ಡರ್ ಬೇಡಿಕೆ",
            "smart_match_score" to "AI ಸ್ಮಾರ್ಟ್ ಮ್ಯಾಚ್ ಸ್ಕೋರ್",
            "negotiation_tip" to "ಸಮಂಜಸ ಒಪ್ಪಂದದ ಸಲಹೆ",

            "Home" to "ಮುಖಪುಟ",
            "Products" to "ಉತ್ಪನ್ನಗಳು",
            "Add" to "ಸೇರಿಸಿ",
            "Circles" to "ಗುಂಪುಗಳು",
            "Profile" to "ಪ್ರೊಫೈಲ್",
            "Explore" to "ಅನ್ವೇಷಿಸಿ",
            "Post RFQ" to "ಬೇಡಿಕೆ ಸಲ್ಲಿಸಿ",
            "Chat" to "ಸಂವಾದ",
            "Impact" to "ಪರಿಣಾಮ",
            "Schemes" to "ಯೋಜನೆಗಳು",
            "Notifications" to "ಸೂಚನೆಗಳು",
            "Save" to "ಉಳಿಸಿ",
            "Cancel" to "ರದ್ದುಮಾಡಿ",
            "Back" to "ಹಿಂದೆ",
            "Next" to "ಮುಂದೆ",
            "Publish" to "ಪ್ರಕಟಿಸಿ",
            "Take Photo" to "ಫೋಟೋ ತೆಗೆಯಿರಿ",
            "Enhance Photo" to "ಚಿತ್ರ ಸುಧಾರಿಸಿ",
            "Generate Story" to "ಕಥೆ ರಚಿಸಿ",
            "View Details" to "ವಿವರ ನೋಡಿ",
            "Login" to "ಲಾಗಿನ್",
            "Register" to "ನೋಂದಣಿ",
            "Logout" to "ಲಾಗ್ ಔಟ್",
            "Filter" to "ಫಿಲ್ಟರ್",
            "Search" to "ಹುಡುಕಿ",
            "Order Now" to "ಈಗಲೇ ಆರ್ಡರ್ ಮಾಡಿ",
            "Call" to "ಕರೆ ಮಾಡಿ",
            "Message" to "ಸಂದೇಶ ಕಳುಹಿಸಿ",
            "Download QR" to "QR ಡೌನ್‌ಲೋಡ್",
            "Share" to "ಹಂಚಿಕೊಳ್ಳಿ",
            "Delete" to "ಅಳಿಸಿ",
            "Edit" to "ತಿದ್ದಿ",
            "Camera Guidance" to "ಕ್ಯಾಮೆರಾ ಮಾರ್ಗದರ್ಶನ",
            "Studio Pro" to "ಸ್ಟುಡಿಯೋ ಪ್ರೊ",
            "Heritage Warm" to "ಸಾಂಪ್ರದಾಯಿಕ ಹೊಳಪು",
            "Vibrant Detail" to "ವರ್ಣಮಯ ವಿವರ",
            "Move closer" to "ನೇಯ್ಗೆಯ ವಿವರಗಳಿಗೆ ಕ್ಯಾಮೆರಾವನ್ನು ಹತ್ತಿರ ತನ್ನಿ",
            "Hold steady" to "ಕ್ಯಾಮೆರಾವನ್ನು ಅಲುಗಾಡಿಸದೆ ಹಿಡಿಯಿರಿ",
            "Too dark" to "ಬೆಳಕು ಕಡಿಮೆಯಿದೆ. ಬೆಳಕಿಗೆ ಬನ್ನಿ ಅಥವಾ ಫ್ಲ್ಯಾಷ್ ಆನ್ ಮಾಡಿ",
            "Too bright" to "ಹೆಚ್ಚಿನ ಬೆಳಕಿದೆ. ನೇರ ಸೂರ್ಯನ ಬೆಳಕಿನಿಂದ ಸ್ವಲ್ಪ ಸರಿಯಿರಿ",
            "Perfect shot" to "ಸರಿಯಾದ ಕೋನ! ಈಗ ಫೋಟೋ ತೆಗೆಯಿರಿ",

            "Welcome to HaathSe" to "ಹಾತ್‌ಸೆಗೆ ಸುಸ್ವಾಗತ",
            "Made by hand. Powered by people and AI." to "ಕೈಯಿಂದ ನಿರ್ಮಿತ. AI ತಂತ್ರಜ್ಞಾನದ ಶಕ್ತಿ.",
            "Choose your role to get started" to "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆರಿಸಿ",
            "I am an Artisan / Maker" to "ನಾನು ಒಬ್ಬ ಕುಶಲಕರ್ಮಿ / ತಯಾರಕ",
            "I am a B2B Buyer / Retailer" to "ನಾನು B2B ಖರೀದಿದಾರ / ವ್ಯಾಪಾರಿ",
            "Ministry & NGO Monitor" to "ಸರ್ಕಾರಿ ಮತ್ತು NGO ಮೇಲ್ವಿಚಾರಣೆ",
            "Sell crafts, get fair prices, create digital passport" to "ಕರಕುಶಲ ವಸ್ತುಗಳನ್ನು ಮಾರಿ, ಸಮಂಜಸ ಬೆಲೆ ಪಡೆಯಿರಿ, ಡಿಜಿಟಲ್ ಪಾಸ್‌ಪೋರ್ಟ್ ಪಡೆಯಿರಿ",
            "Source authentic handmade heritage goods directly" to "ನೇರವಾಗಿ ನೈಜ ಕರಕುಶಲ ವಸ್ತುಗಳನ್ನು ಖರೀದಿಸಿ",
            "Track artisan clusters, sales impact and GI verification" to "ಕುಶಲಕರ್ಮಿ ಗುಂಪುಗಳು ಮತ್ತು ಮಾರಾಟದ ಪ್ರಭಾವವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ",
            "Enter Artisan Studio" to "ಕುಶಲಕರ್ಮಿ ಸ್ಟುಡಿಯೋಗೆ ಪ್ರವೇಶಿಸಿ",
            "Enter Buyer Portal" to "ಖರೀದಿದಾರರ ಪೋರ್ಟಲ್‌ಗೆ ಪ್ರವೇಶಿಸಿ",
            "Enter Impact Hub" to "ಇಂಪ್ಯಾಕ್ಟ್ ಹಬ್‌ಗೆ ಪ್ರವೇಶಿಸಿ"
        ),
        SupportedLanguage.MALAYALAM to mapOf(
            "app_title" to "HaathSe (ഹാത്ത്‌സെ)",
            "tagline" to "നിങ്ങളുടെ കരകൗശലം. നിങ്ങളുടെ കഥ. നിങ്ങളുടെ ബിസിനസ്സ്.",
            "role_artisan" to "കരകൗശല സ്റ്റുഡിയോ",
            "role_buyer" to "B2B വാങ്ങുന്നയാളുടെ പോർട്ടൽ",
            "role_admin" to "സർക്കാർ / NGO പോർട്ടൽ",
            "good_morning" to "നമസ്കാരം",
            "business_today" to "ഇന്നത്തെ ബിസിനസ്സ്",
            "estimated_sales" to "പ്രതീക്ഷിക്കുന്ന വിൽപ്പന",
            "active_products" to "ഉൽപ്പന്നങ്ങൾ",
            "buyer_requests" to "വാങ്ങുന്നയാളുടെ ആവശ്യങ്ങൾ",
            "sell_new_product" to "ഉൽപ്പന്നം വിൽക്കുക",
            "speak_about_product" to "ഉൽപ്പന്നത്തെക്കുറിച്ച് സംസാരിക്കുക",
            "ai_coach_tip" to "AI ബിസിനസ്സ് ഉപദേശം",
            "my_products" to "എന്റെ ഉൽപ്പന്നങ്ങൾ",
            "orders" to "ഓർഡറുകൾ",
            "materials_ledger" to "അസംസ്കൃത വസ്തുക്കൾ",
            "simple_mode" to "ലളിതമായ വോയ്‌സ് മോഡ്",
            "craft_map" to "കരകൗശല മാപ്പ്",
            "govt_schemes" to "സർക്കാർ പദ്ധതികൾ",
            "qr_story" to "ക്രാഫ്റ്റ് QR പാസ്‌പോർട്ട്",
            "listing_score" to "AI ലിസ്റ്റിംഗ് സ്കോർ",
            "fair_price" to "ന്യായമായ വില",
            "publish_button" to "വിപണിയിൽ പ്രസിദ്ധീകരിക്കുക",
            "verified_badge" to "സാക്ഷ്യപ്പെടുത്തിയത്",
            "quick_sale" to "വേഗത്തിലുള്ള വിൽപ്പന",
            "fair_value" to "ന്യായമായ മൂല്യം",
            "premium" to "പ്രീമിയം",
            "voice_recording_hint" to "മൈക് അമർത്തി മലയാളത്തിൽ പറയൂ...",
            "audio_read_aloud" to "കേൾക്കുക",
            "translating_to_buyer" to "വാങ്ങുന്നയാൾക്കായി വിവർത്തനം ചെയ്തത്",
            "minimum_sustainable_price" to "കുറഞ്ഞ സുസ്ഥിര വില",
            "raw_materials" to "അസംസ്കൃത വസ്തുക്കൾ",
            "craft_story" to "കരകൗശലത്തിന്റെ കഥ",
            "rfq_bulk_request" to "ബൾക്ക് ഓർഡർ ആവശ്യം",
            "smart_match_score" to "AI സ്മാർട്ട് മാച്ച് സ്കോർ",
            "negotiation_tip" to "വിലപേശൽ ഉപദേശം",

            "Home" to "ഹോം",
            "Products" to "ഉൽപ്പന്നങ്ങൾ",
            "Add" to "ചേർക്കുക",
            "Circles" to "കൂട്ടായ്മകൾ",
            "Profile" to "പ്രൊഫൈൽ",
            "Explore" to "തിരയുക",
            "Post RFQ" to "ആവശ്യം അറിയിക്കുക",
            "Chat" to "ചാറ്റ്",
            "Impact" to "സ്വാധീനം",
            "Schemes" to "പദ്ധതികൾ",
            "Notifications" to "അറിയിപ്പുകൾ",
            "Save" to "സേവ് ചെയ്യുക",
            "Cancel" to "റദ്ദാക്കുക",
            "Back" to "പിന്നോട്ട്",
            "Next" to "അടുത്തത്",
            "Publish" to "പ്രസിദ്ധീകരിക്കുക",
            "Take Photo" to "ഫോട്ടോ എടുക്കുക",
            "Enhance Photo" to "ഫോട്ടോ മിനുക്കുക",
            "Generate Story" to "കഥ നിർമ്മിക്കുക",
            "View Details" to "വിശദാംശങ്ങൾ കാണുക",
            "Login" to "ലോഗിൻ",
            "Register" to "രജിസ്റ്റർ",
            "Logout" to "ലോഗ് ഔട്ട്",
            "Filter" to "ഫിൽട്ടർ",
            "Search" to "തിരയുക",
            "Order Now" to "ഓർഡർ ചെയ്യുക",
            "Call" to "വിളിക്കുക",
            "Message" to "സന്ദേശം അയക്കുക",
            "Download QR" to "QR ഡൗൺലോഡ് ചെയ്യുക",
            "Share" to "പങ്കുവെക്കുക",
            "Delete" to "ഡിലീറ്റ് ചെയ്യുക",
            "Edit" to "എഡിറ്റ് ചെയ്യുക",
            "Camera Guidance" to "ക്യാമറ മാർഗ്ഗനിർദ്ദേശം",
            "Studio Pro" to "സ്റ്റുഡിയോ പ്രോ",
            "Heritage Warm" to "പൈതൃക തിളക്കം",
            "Vibrant Detail" to "സൂക്ഷ്മ വർണ്ണങ്ങൾ",
            "Move closer" to "സൂക്ഷ്മ നെയ്ത്ത് പകർത്താൻ ക്യാമറ അല്പം അടുപ്പിക്കുക",
            "Hold steady" to "ക്യാമറ ഇളകാതെ നേരെ പിടിക്കുക",
            "Too dark" to "വെളിച്ചം കുറവാണ്. വെളിച്ചത്തിലേക്ക് മാറുക അല്ലെങ്കിൽ ഫ്ലാഷ് ഓൺ ചെയ്യുക",
            "Too bright" to "അമിത വെളിച്ചം. സൂര്യപ്രകാശത്തിൽ നിന്ന് അല്പം മാറുക",
            "Perfect shot" to "കൃത്യമായ ആംഗിൾ! ഇപ്പോൾ ഫോട്ടോ എടുക്കൂ",

            "Welcome to HaathSe" to "ഹാത്ത്‌സെയിലേക്ക് സ്വാഗതം",
            "Made by hand. Powered by people and AI." to "കൈകൊണ്ട് തീർത്തത്. AI കരുത്തോടെ.",
            "Choose your role to get started" to "തുടങ്ങാൻ നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക",
            "I am an Artisan / Maker" to "ഞാൻ ഒരു കരകൗശല വിദഗ്ദ്ധനാണ്",
            "I am a B2B Buyer / Retailer" to "ഞാൻ ഒരു ബിസിനസ്സ് വാങ്ങുന്നയാളാണ്",
            "Ministry & NGO Monitor" to "സർക്കാർ & NGO നിരീക്ഷണം",
            "Sell crafts, get fair prices, create digital passport" to "ഉൽപ്പന്നങ്ങൾ വിൽക്കൂ, ന്യായവില ഉറപ്പാക്കൂ, ഡിജിറ്റൽ പാസ്‌പോർട്ട് നേടൂ",
            "Source authentic handmade heritage goods directly" to "യഥാർത്ഥ പൈതൃക ഉൽപ്പന്നങ്ങൾ നേരിട്ട് വാങ്ങൂ",
            "Track artisan clusters, sales impact and GI verification" to "കരകൗശല സമൂഹങ്ങളെയും വിപണി പുരോഗതിയെയും നിരീക്ഷിക്കുക",
            "Enter Artisan Studio" to "കരകൗശല സ്റ്റുഡിയോയിലേക്ക് പ്രവേശിക്കുക",
            "Enter Buyer Portal" to "വാങ്ങുന്നയാളുടെ പോർട്ടലിലേക്ക് പ്രവേശിക്കുക",
            "Enter Impact Hub" to "ഇംപാക്ട് ഹബ്ബിലേക്ക് പ്രവേശിക്കുക"
        ),
        SupportedLanguage.BENGALI to mapOf(
            "app_title" to "HaathSe (হাত সে)",
            "tagline" to "আপনার শিল্প। আপনার গল্প। আপনার ব্যবসা।",
            "role_artisan" to "কারিগর স্টুডিও",
            "role_buyer" to "B2B ক্রেতা পোর্টাল",
            "role_admin" to "সরকারি / NGO পোর্টাল",
            "good_morning" to "নমস্কার",
            "business_today" to "আজকের ব্যবসা",
            "estimated_sales" to "আনুমানিক বিক্রয়",
            "active_products" to "পণ্যসমূহ",
            "buyer_requests" to "ক্রেতার অনুরোধ",
            "sell_new_product" to "পণ্য বিক্রি করুন",
            "speak_about_product" to "আপনার পণ্য সম্পর্কে বলুন",
            "ai_coach_tip" to "AI বিজনেস কোচ পরামর্শ",
            "my_products" to "আমার ক্যাটালগ",
            "orders" to "অর্ডার ও স্টক",
            "materials_ledger" to "কাঁচামালের খাতা",
            "simple_mode" to "সহজ ভয়েস মোড",
            "craft_map" to "ভারত শিল্প মানচিত্র",
            "govt_schemes" to "সরকারি যোজনা",
            "qr_story" to "শিল্প QR পাসপোর্ট",
            "listing_score" to "AI লিস্টিং স্কোর",
            "fair_price" to "ন্যায্য টেকসই মূল্য",
            "publish_button" to "B2B বাজারে প্রকাশ করুন",
            "verified_badge" to "যাচাইকৃত ঐতিহ্যবাহী শিল্প",
            "quick_sale" to "দ্রুত বিক্রয়",
            "fair_value" to "ন্যায্য মূল্য",
            "premium" to "প্রিমিয়াম মূল্য",
            "voice_recording_hint" to "মাইক টিপে বাংলায় বলুন...",
            "audio_read_aloud" to "অডিও শুনুন",
            "translating_to_buyer" to "ক্রেতার জন্য অনূদিত",
            "minimum_sustainable_price" to "ন্যূনতম টেকসই মূল্য",
            "raw_materials" to "কাঁচামাল",
            "craft_story" to "ঐতিহ্যের গল্প",
            "rfq_bulk_request" to "বাল্ক অর্ডার অনুরোধ",
            "smart_match_score" to "AI স্মার্ট ম্যাচ স্কোর",
            "negotiation_tip" to "সঠিক দামের পরামর্শ",

            "Home" to "হোম",
            "Products" to "পণ্য",
            "Add" to "যুক্ত করুন",
            "Circles" to "মণ্ডলী",
            "Profile" to "প্রোফাইল",
            "Explore" to "অন্বেষণ",
            "Post RFQ" to "চাহিদা জানান",
            "Chat" to "চ্যাট",
            "Impact" to "প্রভাব",
            "Schemes" to "যোজনা",
            "Notifications" to "বিজ্ঞপ্তি",
            "Save" to "সংরক্ষণ",
            "Cancel" to "বাতিল",
            "Back" to "পেছনে",
            "Next" to "পরবর্তী",
            "Publish" to "প্রকাশ করুন",
            "Take Photo" to "ছবি তুলুন",
            "Enhance Photo" to "ছবি সুন্দর করুন",
            "Generate Story" to "গল্প তৈরি করুন",
            "View Details" to "বিস্তারিত দেখুন",
            "Login" to "লগইন",
            "Register" to "রেজিস্টার",
            "Logout" to "লগ আউট",
            "Filter" to "ফিল্টার",
            "Search" to "অনুসন্ধান",
            "Order Now" to "অর্ডার করুন",
            "Call" to "কল করুন",
            "Message" to "বার্তা পাঠান",
            "Download QR" to "QR ডাউনলোড",
            "Share" to "শেয়ার করুন",
            "Delete" to "মুছে ফেলুন",
            "Edit" to "সম্পাদনা",
            "Camera Guidance" to "ক্যামেরা নির্দেশিকা",
            "Studio Pro" to "স্টুডিও প্রো",
            "Heritage Warm" to "ঐতিহ্যবাহী উজ্জ্বলতা",
            "Vibrant Detail" to "উজ্জ্বল সূক্ষ্মতা",
            "Move closer" to "সূক্ষ্ম বুননের জন্য ক্যামেরা কিছুটা কাছে আনুন",
            "Hold steady" to "ক্যামেরা স্থির এবং সোজা রাখুন",
            "Too dark" to "আলো কম। আলোতে আসুন বা ফ্ল্যাশ চালু করুন",
            "Too bright" to "অতিরিক্ত আলো। সরাসরি রোদ থেকে কিছুটা সরুন",
            "Perfect shot" to "একদম সঠিক ফ্রেম! এখন ছবি তুলুন",

            "Welcome to HaathSe" to "হাত সে-তে স্বাগতম",
            "Made by hand. Powered by people and AI." to "হাতে তৈরি। AI প্রযুক্তির শক্তিতে সমৃদ্ধ।",
            "Choose your role to get started" to "শুরু করতে আপনার ভূমিকা বেছে নিন",
            "I am an Artisan / Maker" to "আমি একজন কারিগর / প্রস্তুতকারক",
            "I am a B2B Buyer / Retailer" to "আমি একজন B2B ক্রেতা / ব্যবসায়ী",
            "Ministry & NGO Monitor" to "সরকারি ও NGO পর্যবেক্ষণ",
            "Sell crafts, get fair prices, create digital passport" to "শিল্প বিক্রি করুন, সঠিক মূল্য পান এবং ডিজিটাল পাসপোর্ট তৈরি করুন",
            "Source authentic handmade heritage goods directly" to "সরাসরি আসল হস্তশিল্প পণ্য সংগ্রহ করুন",
            "Track artisan clusters, sales impact and GI verification" to "কারিগর দল ও বিক্রয় প্রভাব ট্র্যাক করুন",
            "Enter Artisan Studio" to "কারিগর স্টুডিওতে যান",
            "Enter Buyer Portal" to "ক্রেতা পোর্টালে যান",
            "Enter Impact Hub" to "ইমপ্যাক্ট হাবে যান"
        ),
        SupportedLanguage.MARATHI to mapOf(
            "app_title" to "HaathSe (हात से)",
            "tagline" to "तुमची कला. तुमची गोष्ट. तुमचा व्यवसाय.",
            "role_artisan" to "कारागीर स्टुडिओ",
            "role_buyer" to "B2B खरेदीदार पोर्टल",
            "role_admin" to "मंत्रालय / NGO पोर्टल",
            "good_morning" to "नमस्कार",
            "business_today" to "आजचा व्यवसाय",
            "estimated_sales" to "अंदाजे विक्री",
            "active_products" to "उत्पादने",
            "buyer_requests" to "खरेदीदार विनंत्या",
            "sell_new_product" to "उत्पादन विका",
            "speak_about_product" to "उत्पादनाबद्दल बोला",
            "ai_coach_tip" to "AI व्यवसाय सल्ला",
            "my_products" to "माझी उत्पादने",
            "orders" to "ऑर्डर्स",
            "materials_ledger" to "कच्चा माल नोंदवही",
            "simple_mode" to "सोपा व्हॉईस मोड",
            "craft_map" to "भारत हस्तकला नकाशा",
            "govt_schemes" to "सरकारी योजना",
            "qr_story" to "शिल्प QR पासपोर्ट",
            "listing_score" to "AI लिस्टिंग स्कोअर",
            "fair_price" to "वाजवी शाश्वत किंमत",
            "publish_button" to "B2B बाजारात प्रकाशित करा",
            "verified_badge" to "प्रमाणित पारंपारिक कला",
            "quick_sale" to "जलद विक्री",
            "fair_value" to "वाजवी मूल्य",
            "premium" to "प्रीमियम मूल्य",
            "voice_recording_hint" to "माईक दाबा आणि मराठीत बोला...",
            "audio_read_aloud" to "ऑडिओ ऐका",
            "translating_to_buyer" to "खरेदीदारासाठी भाषांतरित",
            "minimum_sustainable_price" to "किमान शाश्वत किंमत",
            "raw_materials" to "कच्चा माल",
            "craft_story" to "कलेची कथा",
            "rfq_bulk_request" to "मोठ्या ऑर्डरची मागणी",
            "smart_match_score" to "AI स्मार्ट मॅच स्कोअर",
            "negotiation_tip" to "योग्य सौद्याचा सल्ला",

            "Home" to "मुख्यपृष्ठ",
            "Products" to "उत्पादने",
            "Add" to "जोडा",
            "Circles" to "मंडळे",
            "Profile" to "प्रोफाइल",
            "Explore" to "शोधा",
            "Post RFQ" to "मागणी पाठवा",
            "Chat" to "चॅट",
            "Impact" to "प्रभाव",
            "Schemes" to "योजना",
            "Notifications" to "सूचना",
            "Save" to "जतन करा",
            "Cancel" to "रद्द करा",
            "Back" to "मागे",
            "Next" to "पुढे",
            "Publish" to "प्रकाशित करा",
            "Take Photo" to "फोटो काढा",
            "Enhance Photo" to "फोटो सुधारा",
            "Generate Story" to "कथा तयार करा",
            "View Details" to "तपशील पहा",
            "Login" to "लॉगिन",
            "Register" to "नोंदणी",
            "Logout" to "लॉग आउट",
            "Filter" to "फिल्टर",
            "Search" to "शोधा",
            "Order Now" to "आता ऑर्डर करा",
            "Call" to "कॉल करा",
            "Message" to "संदेश पाठवा",
            "Download QR" to "QR डाउनलोड करा",
            "Share" to "शेअर करा",
            "Delete" to "हटवा",
            "Edit" to "संपादित करा",
            "Camera Guidance" to "कॅमेरा मार्गदर्शन",
            "Studio Pro" to "स्टुडिओ प्रो",
            "Heritage Warm" to "पारंपारिक चमक",
            "Vibrant Detail" to "सुस्पष्ट रंग",
            "Move closer" to "विणकामाच्या बारीक तपशीलांसाठी कॅमेरा थोडा जवळ आणा",
            "Hold steady" to "कॅमेरा न हलवता सरळ धरा",
            "Too dark" to "प्रकाश कमी आहे. प्रकाशात या किंवा फ्लॅश चालू करा",
            "Too bright" to "जास्त प्रकाश आहे. थेट सूर्यप्रकाशापासून थोडे दूर जा",
            "Perfect shot" to "उत्कृष्ट फ्रेमिंग! आता फोटो काढा",

            "Welcome to HaathSe" to "हात से मध्ये आपले स्वागत आहे",
            "Made by hand. Powered by people and AI." to "हाताने तयार केलेले. AI तंत्रज्ञानाने समृद्ध.",
            "Choose your role to get started" to "सुरुवात करण्यासाठी तुमची भूमिका निवडा",
            "I am an Artisan / Maker" to "मी एक कारागीर / निर्माता आहे",
            "I am a B2B Buyer / Retailer" to "मी एक B2B खरेदीदार / व्यापारी आहे",
            "Ministry & NGO Monitor" to "मंत्रालय आणि NGO पोर्टल",
            "Sell crafts, get fair prices, create digital passport" to "कला विका, योग्य भाव मिळवा आणि डिजिटल पासपोर्ट बनवा",
            "Source authentic handmade heritage goods directly" to "थेट अस्सल हस्तकला उत्पादने खरेदी करा",
            "Track artisan clusters, sales impact and GI verification" to "कारागीर गट आणि विक्रीचा प्रभाव ट्रॅक करा",
            "Enter Artisan Studio" to "कारागीर स्टुडिओमध्ये जा",
            "Enter Buyer Portal" to "खरेदीदार पोर्टलमध्ये जा",
            "Enter Impact Hub" to "इम्पॅक्ट हबमध्ये जा"
        ),
        SupportedLanguage.GUJARATI to mapOf(
            "app_title" to "HaathSe (હાથ સે)",
            "tagline" to "તમારી કળા. તમારી વાર્તા. તમારો વ્યવસાય.",
            "role_artisan" to "કારીગર સ્ટુડિયો",
            "role_buyer" to "B2B ખરીદદાર પોર્ટલ",
            "role_admin" to "મંત્રાલય / NGO પોર્ટલ",
            "good_morning" to "નમસ્તે",
            "business_today" to "આજનો વેપાર",
            "estimated_sales" to "અંદાજિત વેચાણ",
            "active_products" to "ઉત્પાદનો",
            "buyer_requests" to "ખરીદદાર વિનંતીઓ",
            "sell_new_product" to "ઉત્પાદન વેચો",
            "speak_about_product" to "ઉત્પાદન વિશે બોલો",
            "ai_coach_tip" to "AI બિઝનેસ કોચ સલાહ",
            "my_products" to "મારા ઉત્પાદનો",
            "orders" to "ઓર્ડર્સ",
            "materials_ledger" to "કાચો માલ ખાતાવહી",
            "simple_mode" to "સરળ વૉઇસ મોડ",
            "craft_map" to "ભારત હસ્તકલા નકશો",
            "govt_schemes" to "સરકારી યોજનાઓ",
            "qr_story" to "શિલ્પ QR પાસપોર્ટ",
            "listing_score" to "AI લિસ્ટિંગ સ્કોર",
            "fair_price" to "વાજબી ટકાઉ કિંમત",
            "publish_button" to "B2B માર્કેટમાં મૂકો",
            "verified_badge" to "પ્રમાણિત પરંપરાગત કળા",
            "quick_sale" to "ઝડપી વેચાણ",
            "fair_value" to "વાજબી કિંમત",
            "premium" to "પ્રીમિયમ કિંમત",
            "voice_recording_hint" to "માઇક દબાવીને ગુજરાતીમાં બોલો...",
            "audio_read_aloud" to "ઓડિયો સાંભળો",
            "translating_to_buyer" to "ખરીદદાર માટે અનુવાદિત",
            "minimum_sustainable_price" to "ન્યૂનતમ ટકાઉ કિંમત",
            "raw_materials" to "કાચો માલ",
            "craft_story" to "કળાની વાર્તા",
            "rfq_bulk_request" to "જથ્થાબંધ ઓર્ડર વિનંતી",
            "smart_match_score" to "AI સ્માર્ટ મેચ સ્કોર",
            "negotiation_tip" to "વાજબી સોદાની સલાહ",

            "Home" to "હોમ",
            "Products" to "ઉત્પાદનો",
            "Add" to "ઉમેરો",
            "Circles" to "મંડળો",
            "Profile" to "પ્રોફાઇલ",
            "Explore" to "શોધો",
            "Post RFQ" to "માંગણી મોકલો",
            "Chat" to "ચેટ",
            "Impact" to "અસર",
            "Schemes" to "યોજનાઓ",
            "Notifications" to "સૂચનાઓ",
            "Save" to "સાચવો",
            "Cancel" to "રદ કરો",
            "Back" to "પાછળ",
            "Next" to "આગળ",
            "Publish" to "પ્રકાશિત કરો",
            "Take Photo" to "ફોટો લો",
            "Enhance Photo" to "ફોટો સુધારો",
            "Generate Story" to "વાર્તા બનાવો",
            "View Details" to "વિગતો જુઓ",
            "Login" to "લૉગિન",
            "Register" to "નોંધણી",
            "Logout" to "લૉગ આઉટ",
            "Filter" to "ફિલ્ટર",
            "Search" to "શોધો",
            "Order Now" to "ઓર્ડર કરો",
            "Call" to "કૉલ કરો",
            "Message" to "સંદેશ મોકલો",
            "Download QR" to "QR ડાઉનલોડ",
            "Share" to "શેર કરો",
            "Delete" to "કાઢી નાખો",
            "Edit" to "સંપાદિત કરો",
            "Camera Guidance" to "કેમેરા માર્ગદર્શન",
            "Studio Pro" to "સ્ટુડિયો પ્રો",
            "Heritage Warm" to "વારસાગત ચમક",
            "Vibrant Detail" to "તેજસ્વી વિગત",
            "Move closer" to "ઝીણી વણાટ વિગતો માટે કેમેરાને થોડો નજીક લાવો",
            "Hold steady" to "કેમેરાને હલાવ્યા વિના સીધો પકડો",
            "Too dark" to "પ્રકાશ ઓછો છે. પ્રકાશમાં આવો અથવા ફ્લેશ ચાલુ કરો",
            "Too bright" to "વધારે પડતો પ્રકાશ છે. સીધા સૂર્યપ્રકાશથી સહેજ ખસો",
            "Perfect shot" to "એકદમ યોગ્ય ફ્રેમિંગ! હવે ફોટો ખેંચો",

            "Welcome to HaathSe" to "હાથ સે માં આપનું સ્વાગત છે",
            "Made by hand. Powered by people and AI." to "હાથે બનાવેલું. AI ટેકનોલોજીની શક્તિ.",
            "Choose your role to get started" to "શરૂ કરવા માટે તમારી ભૂમિકા પસંદ કરો",
            "I am an Artisan / Maker" to "હું એક કારીગર / ઉત્પાદક છું",
            "I am a B2B Buyer / Retailer" to "હું એક B2B ખરીદદાર / વેપારી છું",
            "Ministry & NGO Monitor" to "મંત્રાલય અને NGO પોર્ટલ",
            "Sell crafts, get fair prices, create digital passport" to "કળા વેચો, વાજબી કિંમત મેળવો અને ડિજિટલ પાસપોર્ટ બનાવો",
            "Source authentic handmade heritage goods directly" to "સીધા અસલ પરંપરાગત હસ્તકલા ઉત્પાદનો ખરીદો",
            "Track artisan clusters, sales impact and GI verification" to "કારીગર જૂથો અને વેચાણ પ્રભાવનું નિરીક્ષણ કરો",
            "Enter Artisan Studio" to "કારીગર સ્ટુડિયોમાં જાઓ",
            "Enter Buyer Portal" to "ખરીદદાર પોર્ટલમાં જાઓ",
            "Enter Impact Hub" to "ઈમ્પેક્ટ હબમાં જાઓ"
        ),
        SupportedLanguage.PUNJABI to mapOf(
            "app_title" to "HaathSe (ਹਾਥ ਸੇ)",
            "tagline" to "ਤੁਹਾਡੀ ਕਲਾ। ਤੁਹਾਡੀ ਕਹਾਣੀ। ਤੁਹਾਡਾ ਕਾਰੋਬਾਰ।",
            "role_artisan" to "ਕਾਰੀਗਰ ਸਟੂਡੀਓ",
            "role_buyer" to "B2B ਖਰੀਦਦਾਰ ਪੋਰਟਲ",
            "role_admin" to "ਸਰਕਾਰੀ / NGO ਪੋਰਟਲ",
            "good_morning" to "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
            "business_today" to "ਅੱਜ ਦਾ ਕਾਰੋਬਾਰ",
            "estimated_sales" to "ਅੰਦਾਜ਼ਨ ਵਿਕਰੀ",
            "active_products" to "ਉਤਪਾਦ",
            "buyer_requests" to "ਖਰੀਦਦਾਰ ਬੇਨਤੀਆਂ",
            "sell_new_product" to "ਉਤਪਾਦ ਵੇਚੋ",
            "speak_about_product" to "ਉਤਪਾਦ ਬਾਰੇ ਬੋਲੋ",
            "ai_coach_tip" to "AI ਬਿਜ਼ਨਸ ਕੋਚ ਸਲਾਹ",
            "my_products" to "ਮੇਰੇ ਉਤਪਾਦ",
            "orders" to "ਆਰਡਰ",
            "materials_ledger" to "ਕੱਚੇ ਮਾਲ ਦਾ ਖਾਤਾ",
            "simple_mode" to "ਸਧਾਰਨ ਆਵਾਜ਼ ਮੋਡ",
            "craft_map" to "ਭਾਰਤ ਦਸਤਕਾਰੀ ਨਕਸ਼ਾ",
            "govt_schemes" to "ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
            "qr_story" to "ਕਲਾ QR ਪਾਸਪੋਰਟ",
            "listing_score" to "AI ਲਿਸਟਿੰਗ ਸਕੋਰ",
            "fair_price" to "ਵਾਜਬ ਟਿਕਾਊ ਕੀਮਤ",
            "publish_button" to "B2B ਬਾਜ਼ਾਰ ਵਿੱਚ ਪਾਓ",
            "verified_badge" to "ਪ੍ਰਮਾਣਿਤ ਵਿਰਾਸਤ",
            "quick_sale" to "ਤੁਰੰਤ ਵਿਕਰੀ",
            "fair_value" to "ਵਾਜਬ ਮੁੱਲ",
            "premium" to "ਪ੍ਰੀਮੀਅਮ ਮੁੱਲ",
            "voice_recording_hint" to "ਮਾਈਕ ਦਬਾਓ ਤੇ ਪੰਜਾਬੀ ਵਿੱਚ ਬੋਲੋ...",
            "audio_read_aloud" to "ਆਵਾਜ਼ ਸੁਣੋ",
            "translating_to_buyer" to "ਖਰੀਦਦਾਰ ਲਈ ਅਨੁਵਾਦਿਤ",
            "minimum_sustainable_price" to "ਘੱਟੋ-ਘੱਟ ਟਿਕਾਊ ਕੀਮਤ",
            "raw_materials" to "ਕੱਚਾ ਮਾਲ",
            "craft_story" to "ਕਲਾ ਦੀ ਕਹਾਣੀ",
            "rfq_bulk_request" to "ਥੋਕ ਆਰਡਰ ਬੇਨਤੀ",
            "smart_match_score" to "AI ਸਮਾਰਟ ਮੈਚ ਸਕੋਰ",
            "negotiation_tip" to "ਵਾਜਬ ਸੌਦੇ ਦੀ ਸਲਾਹ",

            "Home" to "ਘਰ",
            "Products" to "ਉਤਪਾਦ",
            "Add" to "ਜੋੜੋ",
            "Circles" to "ਮੰਡਲੀਆਂ",
            "Profile" to "ਪ੍ਰੋਫਾਈਲ",
            "Explore" to "ਖੋਜੋ",
            "Post RFQ" to "ਮੰਗ ਪਾਓ",
            "Chat" to "ਚੈਟ",
            "Impact" to "ਪ੍ਰਭਾਵ",
            "Schemes" to "ਸਕੀਮਾਂ",
            "Notifications" to "ਸੂਚਨਾਵਾਂ",
            "Save" to "ਸੰਭਾਲੋ",
            "Cancel" to "ਰੱਦ ਕਰੋ",
            "Back" to "ਪਿੱਛੇ",
            "Next" to "ਅੱਗੇ",
            "Publish" to "ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ",
            "Take Photo" to "ਫੋਟੋ ਖਿੱਚੋ",
            "Enhance Photo" to "ਫੋਟੋ ਸੁਧਾਰੋ",
            "Generate Story" to "ਕਹਾਣੀ ਬਣਾਓ",
            "View Details" to "ਵੇਰਵੇ ਦੇਖੋ",
            "Login" to "ਲਾਗਇਨ",
            "Register" to "ਰਜਿਸਟਰ",
            "Logout" to "ਲਾਗ ਆਉਟ",
            "Filter" to "ਫਿਲਟਰ",
            "Search" to "ਖੋਜੋ",
            "Order Now" to "ਹੁਣੇ ਆਰਡਰ ਕਰੋ",
            "Call" to "ਕਾਲ ਕਰੋ",
            "Message" to "ਸੁਨੇਹਾ ਭੇਜੋ",
            "Download QR" to "QR ਡਾਊਨਲੋਡ",
            "Share" to "ਸਾਂਝਾ ਕਰੋ",
            "Delete" to "ਹਟਾਓ",
            "Edit" to "ਸੋਧੋ",
            "Camera Guidance" to "ਕੈਮਰਾ ਮਾਰਗਦਰਸ਼ਨ",
            "Studio Pro" to "ਸਟੂਡੀਓ ਪ੍ਰੋ",
            "Heritage Warm" to "ਵਿਰਾਸਤੀ ਚਮਕ",
            "Vibrant Detail" to "ਸਪਸ਼ਟ ਬਰੀਕੀਆਂ",
            "Move closer" to "ਬਰੀਕ ਬੁਣਤੀ ਲਈ ਕੈਮਰੇ ਨੂੰ ਥੋੜ੍ਹਾ ਨੇੜੇ ਲਿਆਓ",
            "Hold steady" to "ਕੈਮਰੇ ਨੂੰ ਹਿਲਾਏ ਬਿਨਾਂ ਸਿੱਧਾ ਰੱਖੋ",
            "Too dark" to "ਰੋਸ਼ਨੀ ਘੱਟ ਹੈ। ਰੋਸ਼ਨੀ ਵਿੱਚ ਆਓ ਜਾਂ ਫਲੈਸ਼ ਚਾਲੂ ਕਰੋ",
            "Too bright" to "ਬਹੁਤ ਜ਼ਿਆਦਾ ਰੋਸ਼ਨੀ ਹੈ। ਸਿੱਧੀ ਧੁੱਪ ਤੋਂ ਥੋੜ੍ਹਾ ਹਟੋ",
            "Perfect shot" to "ਬਿਲਕੁਲ ਸਹੀ ਫ੍ਰੇਮਿੰਗ! ਹੁਣ ਫੋਟੋ ਲਓ",

            "Welcome to HaathSe" to "ਹਾਥ ਸੇ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
            "Made by hand. Powered by people and AI." to "ਹੱਥੀਂ ਬਣਿਆ। AI ਤਕਨਾਲੋਜੀ ਦੀ ਤਾਕਤ ਨਾਲ।",
            "Choose your role to get started" to "ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ",
            "I am an Artisan / Maker" to "ਮੈਂ ਇੱਕ ਕਾਰੀਗਰ / ਨਿਰਮਾਤਾ ਹਾਂ",
            "I am a B2B Buyer / Retailer" to "ਮੈਂ ਇੱਕ B2B ਖਰੀਦਦਾਰ / ਵਪਾਰੀ ਹਾਂ",
            "Ministry & NGO Monitor" to "ਸਰਕਾਰੀ ਅਤੇ NGO ਪੋਰਟਲ",
            "Sell crafts, get fair prices, create digital passport" to "ਕਲਾ ਵੇਚੋ, ਸਹੀ ਮੁੱਲ ਲਵੋ ਅਤੇ ਡਿਜੀਟਲ ਪਾਸਪੋਰਟ ਬਣਾਓ",
            "Source authentic handmade heritage goods directly" to "ਸਿੱਧੇ ਅਸਲੀ ਦਸਤਕਾਰੀ ਉਤਪਾਦ ਖਰੀਦੋ",
            "Track artisan clusters, sales impact and GI verification" to "ਕਾਰੀਗਰ ਗਰੁੱਪਾਂ ਅਤੇ ਵਿਕਰੀ ਦੇ ਅਸਰ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ",
            "Enter Artisan Studio" to "ਕਾਰੀਗਰ ਸਟੂਡੀਓ ਵਿੱਚ ਜਾਓ",
            "Enter Buyer Portal" to "ਖਰੀਦਦਾਰ ਪੋਰਟਲ ਵਿੱਚ ਜਾਓ",
            "Enter Impact Hub" to "ਇੰਪੈਕਟ ਹੱਬ ਵਿੱਚ ਜਾਓ"
        ),
        SupportedLanguage.ODIA to mapOf(
            "app_title" to "HaathSe (ହାତ ସେ)",
            "tagline" to "ଆପଣଙ୍କ କଳା। ଆପଣଙ୍କ କାହାଣୀ। ଆପଣଙ୍କ ବ୍ୟବସାୟ।",
            "role_artisan" to "କାରିଗର ଷ୍ଟୁଡିଓ",
            "role_buyer" to "B2B କ୍ରେତା ପୋର୍ଟାଲ",
            "role_admin" to "ସରକାରୀ / NGO ପୋର୍ଟାଲ",
            "good_morning" to "ନମସ୍କାର",
            "business_today" to "ଆଜିର ବ୍ୟବସାୟ",
            "estimated_sales" to "ଆନୁମାନିକ ବିକ୍ରୟ",
            "active_products" to "ଉତ୍ପାଦ",
            "buyer_requests" to "କ୍ରେତା ଅନୁରୋଧ",
            "sell_new_product" to "ଉତ୍ପାଦ ବିକ୍ରୟ କରନ୍ତୁ",
            "speak_about_product" to "ଆପଣଙ୍କ ଉତ୍ପାଦ ବିଷୟରେ କୁହନ୍ତୁ",
            "ai_coach_tip" to "AI ବ୍ୟବସାୟ ପରାମର୍ଶ",
            "my_products" to "ମୋର ଉତ୍ପାଦ",
            "orders" to "ଅର୍ଡର",
            "materials_ledger" to "କଞ୍ଚାମାଲ ଖାତା",
            "simple_mode" to "ସରଳ ଭଏସ୍ ମୋଡ୍",
            "craft_map" to "ଭାରତ ହସ୍ତଶିଳ୍ପ ମାନଚିତ୍ର",
            "govt_schemes" to "ସରକାରୀ ଯୋଜନା",
            "qr_story" to "ଶିଳ୍ପ QR ପାସପୋର୍ଟ",
            "listing_score" to "AI ଲିଷ୍ଟିଂ ସ୍କୋର",
            "fair_price" to "ଉପଯୁକ୍ତ ସ୍ଥାୟୀ ମୂଲ୍ୟ",
            "publish_button" to "B2B ବଜାରରେ ପ୍ରକାଶ କରନ୍ତୁ",
            "verified_badge" to "ପ୍ରମାଣିତ ଐତିହ୍ୟ ଶିଳ୍ପ",
            "quick_sale" to "ଶୀଘ୍ର ବିକ୍ରୟ",
            "fair_value" to "ଉଚିତ୍ ମୂଲ୍ୟ",
            "premium" to "ପ୍ରିମିୟମ୍ ମୂଲ୍ୟ",
            "voice_recording_hint" to "ମାଇକ୍ ଦବାଇ ଓଡ଼ିଆରେ କୁହନ୍ତୁ...",
            "audio_read_aloud" to "ଅଡିଓ ଶୁଣନ୍ତୁ",
            "translating_to_buyer" to "କ୍ରେତାଙ୍କ ପାଇଁ ଅନୁବାଦିତ",
            "minimum_sustainable_price" to "ସର୍ବନିମ୍ନ ସ୍ଥାୟୀ ମୂଲ୍ୟ",
            "raw_materials" to "କଞ୍ଚାମାଲ",
            "craft_story" to "ଶିଳ୍ପ ପଛର କାହାଣୀ",
            "rfq_bulk_request" to "ହୋଲସେଲ ଅର୍ଡର ଅନୁରୋଧ",
            "smart_match_score" to "AI ସ୍ମାର୍ଟ ମ୍ୟାଚ୍ ସ୍କୋର",
            "negotiation_tip" to "ସଠିକ୍ ଡିଲ୍ ପରାମର୍ଶ",

            "Home" to "ମୁଖ୍ୟ ପୃଷ୍ଠା",
            "Products" to "ଉତ୍ପାଦ",
            "Add" to "ଯୋଡନ୍ତୁ",
            "Circles" to "ମଣ୍ଡଳୀ",
            "Profile" to "ପ୍ରୋଫାଇଲ୍",
            "Explore" to "ଅନୁସନ୍ଧାନ",
            "Post RFQ" to "ଅନୁରୋଧ ପଠାନ୍ତୁ",
            "Chat" to "ଚାଟ୍",
            "Impact" to "ପ୍ରଭାବ",
            "Schemes" to "ଯୋଜନା",
            "Notifications" to "ବିଜ୍ଞପ୍ତି",
            "Save" to "ସାଇତନ୍ତୁ",
            "Cancel" to "ବାତିଲ୍",
            "Back" to "ପଛକୁ",
            "Next" to "ଆଗକୁ",
            "Publish" to "ପ୍ରକାଶ କରନ୍ତୁ",
            "Take Photo" to "ଫଟୋ ଉଠାନ୍ତୁ",
            "Enhance Photo" to "ଫଟୋ ସୁଧାରନ୍ତୁ",
            "Generate Story" to "କାହାଣୀ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
            "View Details" to "ବିବରଣୀ ଦେଖନ୍ତୁ",
            "Login" to "ଲଗଇନ୍",
            "Register" to "ପଞ୍ଜୀକରଣ",
            "Logout" to "ଲଗ୍ ଆଉଟ୍",
            "Filter" to "ଫିଲ୍ଟର୍",
            "Search" to "ଖୋଜନ୍ତୁ",
            "Order Now" to "ଅର୍ଡର କରନ୍ତୁ",
            "Call" to "କଲ୍ କରନ୍ତୁ",
            "Message" to "ବାର୍ତ୍ତା ପଠାନ୍ତୁ",
            "Download QR" to "QR ଡାଉନଲୋଡ୍",
            "Share" to "ସେୟାର୍ କରନ୍ତୁ",
            "Delete" to "ଲିଭାନ୍ତୁ",
            "Edit" to "ସଂଶୋଧନ କରନ୍ତୁ",
            "Camera Guidance" to "କ୍ୟାମେରା ମାର୍ଗଦର୍ଶନ",
            "Studio Pro" to "ଷ୍ଟୁଡିଓ ପ୍ରୋ",
            "Heritage Warm" to "ପାରମ୍ପରିକ ଉଜ୍ଜ୍ୱଳତା",
            "Vibrant Detail" to "ସୂକ୍ଷ୍ମ ବିବରଣୀ",
            "Move closer" to "ସୂକ୍ଷ୍ମ ବୁଣାକାର୍ଯ୍ୟ ପାଇଁ କ୍ୟାମେରାକୁ ଟିକେ ପାଖକୁ ଆଣନ୍ତୁ",
            "Hold steady" to "କ୍ୟାମେରାକୁ ନ ହଲାଇ ସିଧା ଧରନ୍ତୁ",
            "Too dark" to "ଆଲୋକ କମ୍ ଅଛି। ଆଲୋକକୁ ଆସନ୍ତୁ କିମ୍ବା ଫ୍ଲାସ୍ ଅନ୍ କରନ୍ତୁ",
            "Too bright" to "ଅତ୍ୟଧିକ ଆଲୋକ। ସିଧା ଖରାରୁ ଟିକେ ଦୂରକୁ ଯାଆନ୍ତୁ",
            "Perfect shot" to "ସମ୍ପୂର୍ଣ୍ଣ ସଠିକ୍ ଆଙ୍ଗେଲ୍! ଏବେ ଫଟୋ ଉଠାନ୍ତୁ",

            "Welcome to HaathSe" to "ହାତ ସେରେ ଆପଣଙ୍କୁ ସ୍ୱାଗତ",
            "Made by hand. Powered by people and AI." to "ହାତ ତିଆରି। AI ପ୍ରଯୁକ୍ତିବିଦ୍ୟାର ଶକ୍ତି ସହିତ।",
            "Choose your role to get started" to "ଆରମ୍ଭ କରିବାକୁ ନିଜର ଭୂମିକା ବାଛନ୍ତୁ",
            "I am an Artisan / Maker" to "ମୁଁ ଜଣେ କାରିଗର / ନିର୍ମାତା",
            "I am a B2B Buyer / Retailer" to "ମୁଁ ଜଣେ B2B କ୍ରେତା / ବ୍ୟବସାୟୀ",
            "Ministry & NGO Monitor" to "ସରକାରୀ ଓ NGO ପୋର୍ଟାଲ୍",
            "Sell crafts, get fair prices, create digital passport" to "ହସ୍ତଶିଳ୍ପ ବିକ୍ରୟ କରନ୍ତୁ, ଉପଯୁକ୍ତ ମୂଲ୍ୟ ପାଆନ୍ତୁ ଏବଂ ଡିଜିଟାଲ୍ ପାସପୋର୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ",
            "Source authentic handmade heritage goods directly" to "ସିଧାସଳଖ ଅସଲି ପାରମ୍ପରିକ ହସ୍ତଶିଳ୍ପ ସାମଗ୍ରୀ କିଣନ୍ତୁ",
            "Track artisan clusters, sales impact and GI verification" to "କାରିଗର ଗୋଷ୍ଠୀ ଏବଂ ବିକ୍ରୟ ପ୍ରଭାବ ଉପରେ ନଜର ରଖନ୍ତୁ",
            "Enter Artisan Studio" to "କାରିଗର ଷ୍ଟୁଡିଓକୁ ଯାଆନ୍ତୁ",
            "Enter Buyer Portal" to "କ୍ରେତା ପୋର୍ଟାଲକୁ ଯାଆନ୍ତୁ",
            "Enter Impact Hub" to "ଇମ୍ପାକ୍ଟ ହବକୁ ଯାଆନ୍ତୁ"
        )
    )

    fun getString(lang: SupportedLanguage, key: String): String {
        return tr(key, lang)
    }

    /**
     * Translates any string key, label, or phrase into the chosen target language.
     * Matches exact key, trimmed key, or fallback to English.
     */
    fun tr(textOrKey: String, lang: SupportedLanguage): String {
        if (textOrKey.isBlank()) return textOrKey
        if (lang == SupportedLanguage.ENGLISH) {
            return translations[SupportedLanguage.ENGLISH]?.get(textOrKey)
                ?: translations[SupportedLanguage.ENGLISH]?.get(textOrKey.trim())
                ?: textOrKey
        }

        val langMap = translations[lang] ?: return textOrKey

        // Direct lookup
        langMap[textOrKey]?.let { return it }

        // Trimmed lookup
        langMap[textOrKey.trim()]?.let { return it }

        // Reverse search through English mappings if textOrKey was the English value
        val engMap = translations[SupportedLanguage.ENGLISH]
        if (engMap != null) {
            for ((key, englishVal) in engMap) {
                if (englishVal.equals(textOrKey, ignoreCase = true) || key.equals(textOrKey, ignoreCase = true)) {
                    langMap[key]?.let { return it }
                }
            }
        }

        // Fallback to English value or original
        return engMap?.get(textOrKey) ?: textOrKey
    }

    val demoVoiceTranscripts = mapOf(
        SupportedLanguage.TAMIL to listOf(
            "இது எங்கள் குடும்பத்தின் பாரம்பரிய காஞ்சிபுரம் பட்டு சேலை. இதில் மயில் மற்றும் ருத்ராட்ச ஜரிகை வேலைப்பாடு உள்ளது. நெசவு செய்ய 5 நாட்கள் ஆனது. மூலப்பொருள் பட்டு நூல் செலவு ₹2,100.",
            "இது ஜெய்ப்பூர் நீல மண்பாண்ட பூந்தொட்டி. பாரம்பரிய கோபால்ட் மற்றும் டர்க்காய்ஸ் வண்ணங்களில் கைவினை செய்யப்பட்டது. 3 நாட்கள் உழைப்பு, மூலப்பொருள் செலவு ₹450.",
            "இது சன்னபட்டணா மரத்தால் செய்யப்பட்ட பாரம்பர்ய பொம்மை செட். இயற்கை காய்கறி வண்ணங்கள் பயன்படுத்தப்பட்டுள்ளது. குழந்தைகளுக்கு பாதுகாப்பானது. மூலப்பொருள் ₹280."
        ),
        SupportedLanguage.HINDI to listOf(
            "यह पारंपरिक हाथ से बुनी कांचीपुरम सिल्क साड़ी है जिसमें मोर और रुद्राक्ष ज़री का काम है। इसे बनाने में 5 दिन लगे, कच्चा रेशम धागा ₹2,100 का लगा।",
            "यह जयपुर ब्लू पॉटरी की हस्तनिर्मित सजावटी फूलदान है। पारंपरिक प्राकृतिक रंगों से हाथ से चित्रित। 3 दिन का काम, कच्चा माल ₹450।",
            "यह चन्नापटना लकड़ी का खिलौना सेट है, पूरी तरह से प्राकृतिक वनस्पति रंगों से बना और बच्चों के लिए सुरक्षित है। लागत ₹280।"
        ),
        SupportedLanguage.ENGLISH to listOf(
            "This is an authentic handwoven Kanchipuram silk saree with traditional peacock and rudraksha gold zari motifs. It took 5 days on the handloom. Raw silk thread cost ₹2,100.",
            "This is a handmade Jaipur Blue Pottery decorative floral vase with cobalt and turquoise glaze. 3 days artisan labor, raw material cost ₹450.",
            "This is a handcrafted Channapatna wooden toy set colored with natural vegetable dyes and polished with lacquer. Completely non-toxic. Material cost ₹280."
        ),
        SupportedLanguage.TELUGU to listOf(
            "ఇది మా సాంప్రదాయ కాంచీపురం పట్టు చీర. నెమలి మరియు రుద్రాక్ష జరీ డిజైన్లతో 5 రోజులు మగ్గంపై నేసినది. ముడి పట్టు దారాల ఖర్చు ₹2,100.",
            "ఇది జైపూర్ బ్లూ పాటర్ చేతితో చేసిన అలంకార కుండీ. సాంప్రదాయ సహజ రంగులు, 3 రోజుల శ్రమ, ముడి పదార్థాల ఖర్చు ₹450."
        ),
        SupportedLanguage.KANNADA to listOf(
            "ಇದು ಅಧಿಕೃತ ಕೈಮಗ್ಗ ಕಾಂಚೀಪುರಂ ರೇಷ್ಮೆ ಸೀರೆ. ನವಿಲು ಜರಿ ವಿನ್ಯಾಸ ಹೊಂದಿದ್ದು, 5 ದಿನಗಳ ಶ್ರಮವಿದೆ. ರೇಷ್ಮೆ ದಾರದ ವೆಚ್ಚ ₹2,100.",
            "ಇದು ಚೆನ್ನಪಟ್ಟಣ ಸಾಂಪ್ರದಾಯಿಕ ಮರದ ಆಟಿಕೆ ಸೆಟ್. ನೈಸರ್ಗಿಕ ತರಕಾರಿ ಬಣ್ಣಗಳಿಂದ ತಯಾರಿಸಿದ್ದು ಮಕ್ಕಳ ಸುರಕ್ಷಿತ. ಕಚ್ಚಾ ವಸ್ತು ₹280."
        ),
        SupportedLanguage.MALAYALAM to listOf(
            "ഇത് ഞങ്ങളുടെ പരമ്പരാഗത കാഞ്ചീപുരം പട്ട് സാരിയാണ്. മയിൽ, രുദ്രാക്ഷം സരി വർക്കുകൾ ഉള്ളത്. നെയ്യാൻ 5 ദിവസമെടുത്തു. അസംസ്കൃത പട്ടുനൂൽ ചിലവ് ₹2,100.",
            "ഇത് ജയ്പൂർ ബ്ലൂ പോട്ടറി അലങ്കാര പൂപ്പാത്രമാണ്. സ്വാഭാവിക നിറങ്ങളിൽ കൈകൊണ്ട് വരച്ചത്. 3 ദിവസത്തെ അധ്വാനം, അസംസ്കൃത വസ്തു ₹450."
        ),
        SupportedLanguage.BENGALI to listOf(
            "এটি ঐতিহ্যবাহী হাতে বোনা কাঞ্চিপুরম রেশম শাড়ি। ময়ূর ও রুদ্রাক্ষ জরি নকশা করা। এটি তৈরি করতে ৫ দিন লেগেছে, কাঁচা রেশমের খরচ ₹২,১০০।",
            "এটি জয়পুর ব্লু পটারির তৈরি সুন্দর ফুলদানি। প্রাকৃতিক রঙে হাতে আঁকা। ৩ দিনের পরিশ্রম, কাঁচামাল ₹৪৫০।"
        ),
        SupportedLanguage.MARATHI to listOf(
            "ही अस्सल हाताने विणलेली कांजीवरम सिल्क साडी आहे. यात मोर आणि रुद्राक्ष जरीचे काम आहे. ५ दिवसांचे विणकाम, कच्चा रेशीम खर्च ₹२,१००.",
            "हे जयपूर ब्लू पॉटरीचे हस्तनिर्मित सजावटी फुलदाणी आहे. ३ दिवसांचे श्रम, कच्चा माल ₹४५०."
        ),
        SupportedLanguage.GUJARATI to listOf(
            "આ પરંપરાગત હાથવણાટ કાંચીપુરમ સિલ્ક સાડી છે. મોર અને રુદ્રાક્ષ ઝરી કામ સાથે. બનાવવામાં 5 દિવસ લાગ્યા, કાચો રેશમ દોરો ₹2,100 નો થયો.",
            "આ જયપુર બ્લુ પોટરીની હાથબનાવટ ફ્લાવરદાની છે. કુદરતી રંગોથી બનાવેલી, કાચો માલ ₹450."
        ),
        SupportedLanguage.PUNJABI to listOf(
            "ਇਹ ਪਰੰਪਰਾਗਤ ਹੱਥੀਂ ਬੁਣੀ ਕਾਂਚੀਪੁਰਮ ਸਿਲਕ ਸਾੜੀ ਹੈ। ਮੋਰ ਅਤੇ ਰੁਦਰਾਕਸ਼ ਜ਼ਰੀ ਦੇ ਕੰਮ ਵਾਲੀ। 5 ਦਿਨਾਂ ਦੀ ਮਿਹਨਤ, ਕੱਚੇ ਰੇਸ਼ਮ ਦਾ ਖਰਚਾ ₹2,100।",
            "ਇਹ ਜੈਪੁਰ ਬਲੂ ਪੌਟਰੀ ਦਾ ਸਜਾਵਟੀ ਫੁੱਲਦਾਨ ਹੈ। 3 ਦਿਨਾਂ ਦੀ ਮਿਹਨਤ, ਕੱਚਾ ਮਾਲ ₹450।"
        ),
        SupportedLanguage.ODIA to listOf(
            "ଏହା ଏକ ପାରମ୍ପରିକ ହାତବୁଣା କାଞ୍ଚିପୁରମ୍ ରେଶମ ଶାଢ଼ୀ। ମୟୂର ଓ ରୁଦ୍ରାକ୍ଷ ଜରୀ କାମ ହୋଇଛି। ୫ ଦିନର ପରିଶ୍ରମ, କଞ୍ଚା ରେଶମ ଖର୍ଚ୍ଚ ₹୨,୧୦୦।",
            "ଏହା ଜୟପୁର ବ୍ଲୁ ପଟେରୀ ହାତ ତିଆରି ଫୁଲଦାନୀ। ପ୍ରାକୃତିକ ରଙ୍ଗରେ ଚିତ୍ରିତ, କଞ୍ଚାମାଲ ଖର୍ଚ୍ଚ ₹୪୫୦।"
        )
    )

    fun getVoiceSamples(lang: SupportedLanguage): List<String> {
        return demoVoiceTranscripts[lang] ?: demoVoiceTranscripts[SupportedLanguage.ENGLISH] ?: emptyList()
    }
}
